version: "3.9"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'weighcommu.link'
      #STAGE: 'production'
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=weighcommu
    ports:
      - "5432:5432"
  nginx:
    depends_on:
      - api
      - client
    image: maniizu3110/nginx:v1
    ports:
      - "80:80"
  client:
    image: maniizu3110/client:v1
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  api:
    image: maniizu3110/api:v1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
